name: kwc
version: 0.1.0.0
github: "jhrcek/kwc"
license: BSD3
author: "Jan Hrček"
maintainer: "example@example.com"
copyright: "2018 Jan Hrček"

extra-source-files:
- README.md
- ChangeLog.md

synopsis: Experimental REST client for interaction with KIE Workbench
category: Web
description: Please see the README on Github at <https://github.com/jhrcek/kwc#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- http-client
- http-api-data
- servant
- servant-client
- text

executables:
  example-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
